# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b954b6b4a0a14ac8a218d83bc496f6d5a7129d7afe9ee7281cc7febc04b3a9b9dac05040b55d3d99924e3467eb8abe9c70b631c3435573b7b2bb4361f139fd45

test:
  secret_key_base: 979929e12e7d2a6db1528db5579527620c3589c8d239872efc7b412e75f2c0e93898a3c505340601b560bde17d23d118b718a878723204339a029b64b48cea00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
